### ISSUE TITLE
Authenticator is not a constructor

### ISSUE THREAD

**Issue by laza-niaina** [ericlewis/openai-authenticator#2]
> Error : Authenticator is not a constructor

**This is my code:**
`async function token(){
const {Authenticator}= await  import ("openai-authenticator");
const authenticator = new Authenticator();
console.log(await authenticator.login("myemail@gmail.com", "mypass"));
}`

**Comment by ZirionNeft** [comment]
Module have export this class as default, so you need to get it as well:
```js
const module = await import ("openai-authenticator");
const Authenticator = module.default;
const auth = new Authenticator();
```

**Comment by laza-niaina** [comment]
#Thanks
